apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceserver
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: aceserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: aceserver
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/cp4i/custom-ace-img:5.0
        imagePullPolicy: Always
        name: aceserver
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30     