apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-ace-img-task
spec:
  params:
    - name: namespace
      description: release namespace
      default: cp4i
      type: string
    - name: integrationServerName
      description: name of the integration server
      default: aceserver
    - name: license
      description: license number
      default: L-KSBM-C87FU2
  resources:
    inputs:
    - name: source
      type: git
    outputs:
    - name: image
      type: image
  steps:
    - name: oc
      image: quay.io/openshift/origin-cli:latest
      workingDir: /workspace/source
      script: |
        . ./imgcfg
        cat << EOF | oc apply -f -
        apiVersion: appconnect.ibm.com/v1beta1
        kind: IntegrationServer
        metadata:
          name: $aceappname
          namespace: $(params.namespace)
        spec:
          enableMetrics: true
          license:
            accept: true
            license: $(params.license)
            use: CloudPakForIntegrationNonProduction
          pod:
            containers:
              runtime:
                image: $(resources.outputs.image.url)/$(params.namespace)/$imgname:$imgtag
                imagePullPolicy: Always
                resources:
                  limits:
                    cpu: 300m
                    memory: 350Mi
                  requests:
                    cpu: 300m
                    memory: 300Mi
          adminServerSecure: false
          router:
            timeout: 120s
          designerFlowsOperationMode: disabled
          createDashboardUsers: true
          service:
            endpointType: http
          replicas: 1
          version: 12.0.2.0-r2
        EOF