apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-ace-img-pipeline
spec:
  resources:
  - name: git-repo
    type: git
  - name: image
    type: image
  tasks:
  - name: build-image
    taskRef:
      name: build-ace-img-task
    resources:
      inputs:
      - name: source
        resource: git-repo
      outputs:
      - name: image
        resource: image
    params:
    - name: TLSVERIFY
      value: "false"  