apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    appconnectenterprise: operator-icp4i
    deployment.kubernetes.io/revision: '1'
    serverName: argocd-ace-server-2
  creationTimestamp: '2022-06-26T19:21:26Z'
  generation: 10
  labels:
    app.kubernetes.io/instance: argocd-ace-server-2
    app.kubernetes.io/managed-by: ibm-appconnect
    app.kubernetes.io/name: argocd-ace-server-2
    appconnect.ibm.com/kind: IntegrationServer
    release: argocd-ace-server-2
  managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:appconnectenterprise': {}
            'f:serverName': {}
          'f:labels':
            .: {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/managed-by': {}
            'f:app.kubernetes.io/name': {}
            'f:appconnect.ibm.com/kind': {}
            'f:release': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"32ecf12a-fb17-4464-81c4-982eab048883"}':
              .: {}
              'f:apiVersion': {}
              'f:blockOwnerDeletion': {}
              'f:controller': {}
              'f:kind': {}
              'f:name': {}
              'f:uid': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:replicas': {}
          'f:revisionHistoryLimit': {}
          'f:selector': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:annotations':
                .: {}
                'f:cloudpakId': {}
                'f:cloudpakName': {}
                'f:productChargedContainers': {}
                'f:productCloudpakRatio': {}
                'f:productID': {}
                'f:productMetric': {}
                'f:productName': {}
              'f:labels':
                .: {}
                'f:app.kubernetes.io/instance': {}
                'f:app.kubernetes.io/managed-by': {}
                'f:app.kubernetes.io/name': {}
                'f:appconnect.ibm.com/kind': {}
                'f:release': {}
            'f:spec':
              'f:affinity':
                .: {}
                'f:nodeAffinity':
                  .: {}
                  'f:requiredDuringSchedulingIgnoredDuringExecution':
                    .: {}
                    'f:nodeSelectorTerms': {}
                'f:podAntiAffinity':
                  .: {}
                  'f:preferredDuringSchedulingIgnoredDuringExecution': {}
              'f:containers':
                'k:{"name":"argocd-ace-server-2"}':
                  .: {}
                  'f:env':
                    .: {}
                    'k:{"name":"ACE_ADMIN_SERVER_SECURITY"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"ACE_DEFAULT_APPLICATION_NAME"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"ACE_ENABLE_METRICS"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"ACE_ENABLE_OPEN_TRACING"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"ACE_SERVER_NAME"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"APP_CONNECT_LICENSE_TOGGLES"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"DEFAULT_CONTENT_SERVER"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"DESIGNER_FLOWS_OPERATION_MODE"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"GODEBUG"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"LICENSE"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"LOG_FORMAT"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"MQSI_OVERRIDE_HOSTNAME"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"MQSI_OVERRIDE_HTTP_PORT"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"SERVICE_NAME"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                  'f:image': {}
                  'f:imagePullPolicy': {}
                  'f:livenessProbe':
                    .: {}
                    'f:exec':
                      .: {}
                      'f:command': {}
                    'f:failureThreshold': {}
                    'f:initialDelaySeconds': {}
                    'f:periodSeconds': {}
                    'f:successThreshold': {}
                    'f:timeoutSeconds': {}
                  'f:name': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":7600,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:name': {}
                      'f:protocol': {}
                    'k:{"containerPort":7800,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:name': {}
                      'f:protocol': {}
                    'k:{"containerPort":7843,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:name': {}
                      'f:protocol': {}
                  'f:readinessProbe':
                    .: {}
                    'f:exec':
                      .: {}
                      'f:command': {}
                    'f:failureThreshold': {}
                    'f:initialDelaySeconds': {}
                    'f:periodSeconds': {}
                    'f:successThreshold': {}
                    'f:timeoutSeconds': {}
                  'f:resources':
                    .: {}
                    'f:limits':
                      .: {}
                      'f:cpu': {}
                      'f:ephemeral-storage': {}
                      'f:memory': {}
                    'f:requests':
                      .: {}
                      'f:cpu': {}
                      'f:ephemeral-storage': {}
                      'f:memory': {}
                  'f:securityContext':
                    .: {}
                    'f:allowPrivilegeEscalation': {}
                    'f:capabilities':
                      .: {}
                      'f:drop': {}
                    'f:privileged': {}
                    'f:readOnlyRootFilesystem': {}
                    'f:runAsNonRoot': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
                  'f:volumeMounts':
                    .: {}
                    'k:{"mountPath":"/home/aceuser/ace-server"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                    'k:{"mountPath":"/home/aceuser/initial-config/webusers"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:serviceAccount': {}
              'f:serviceAccountName': {}
              'f:terminationGracePeriodSeconds': {}
              'f:volumes':
                .: {}
                'k:{"name":"webusers"}':
                  .: {}
                  'f:name': {}
                  'f:secret':
                    .: {}
                    'f:defaultMode': {}
                    'f:items': {}
                    'f:secretName': {}
                'k:{"name":"workdir"}':
                  .: {}
                  'f:emptyDir': {}
                  'f:name': {}
      manager: manager
      operation: Update
      time: '2022-06-26T19:21:26Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:updatedReplicas': {}
      manager: kube-controller-manager
      operation: Update
      time: '2022-06-26T19:23:02Z'
  name: argocd-ace-server-2-is
  namespace: auto-poc
  ownerReferences:
    - apiVersion: appconnect.ibm.com/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: IntegrationServer
      name: argocd-ace-server-2
      uid: 32ecf12a-fb17-4464-81c4-982eab048883
  resourceVersion: '115807752'
  uid: a05f5b10-3ae2-490c-a1f7-1ca87ef86ada
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: argocd-ace-server-2
      app.kubernetes.io/managed-by: ibm-appconnect
      app.kubernetes.io/name: argocd-ace-server-2
      release: argocd-ace-server-2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cloudpakId: c8b82d189e7545f0892db9ef2731b90d
        cloudpakName: IBM Cloud Pak for Integration
        productChargedContainers: argocd-ace-server-2
        productCloudpakRatio: '2:3'
        productID: eb5b5e73f62b4dcf8c434c6274a158a7
        productMetric: VIRTUAL_PROCESSOR_CORE
        productName: IBM App Connect Enterprise for non-production
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: argocd-ace-server-2
        app.kubernetes.io/managed-by: ibm-appconnect
        app.kubernetes.io/name: argocd-ace-server-2
        appconnect.ibm.com/kind: IntegrationServer
        release: argocd-ace-server-2
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - s390x
                      - ppc64le
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: argocd-ace-server-2
                    app.kubernetes.io/managed-by: ibm-appconnect
                    app.kubernetes.io/name: argocd-ace-server-2
                    release: argocd-ace-server-2
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - env:
            - name: ACE_DEFAULT_APPLICATION_NAME
              value: DefaultApplication
            - name: ACE_ENABLE_METRICS
              value: 'true'
            - name: ACE_ENABLE_OPEN_TRACING
              value: 'false'
            - name: ACE_SERVER_NAME
              value: argocd-ace-server-2
            - name: DESIGNER_FLOWS_OPERATION_MODE
              value: disabled
            - name: LOG_FORMAT
              value: basic
            - name: SERVICE_NAME
              value: argocd-ace-server-2-is
            - name: LICENSE
              value: accept
            - name: APP_CONNECT_LICENSE_TOGGLES
              value: '{"connector-ibmrpa":1}'
            - name: MQSI_OVERRIDE_HOSTNAME
              value: >-
                argocd-ace-server-2-http-auto-poc.jbs-poc-wdc04-c3c-32x64-0abe335159b03c3875b36f776cdd6d65-0000.us-east.containers.appdomain.cloud
            - name: MQSI_OVERRIDE_HTTP_PORT
              value: '80'
            - name: GODEBUG
              value: x509ignoreCN=0
            - name: ACE_ADMIN_SERVER_SECURITY
              value: 'false'
            - name: DEFAULT_CONTENT_SERVER
              value: 'true'
          image: >-
            image-registry.openshift-image-registry.svc:5000/auto-poc/custom-ace-img:6.0
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - chkacehealthy
            failureThreshold: 1
            initialDelaySeconds: 360
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: argocd-ace-server-2
          ports:
            - containerPort: 7600
              name: webui
              protocol: TCP
            - containerPort: 7800
              name: ace-http
              protocol: TCP
            - containerPort: 7843
              name: ace-https
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - chkacehealthy
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            limits:
              cpu: 300m
              ephemeral-storage: 20Gi
              memory: 350Mi
            requests:
              cpu: 300m
              ephemeral-storage: 5Gi
              memory: 300Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /home/aceuser/initial-config/webusers
              name: webusers
            - mountPath: /home/aceuser/ace-server
              name: workdir
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: argocd-ace-server-2-is
      serviceAccountName: argocd-ace-server-2-is
      terminationGracePeriodSeconds: 30
      volumes:
        - name: webusers
          secret:
            defaultMode: 420
            items:
              - key: adminusers
                path: admin-users.txt
              - key: operatorusers
                path: operator-users.txt
              - key: viewerusers
                path: viewer-users.txt
              - key: editorusers
                path: editor-users.txt
              - key: auditusers
                path: audit-users.txt
            secretName: argocd-ace-server-2-is
        - emptyDir: {}
          name: workdir
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2022-06-26T19:22:52Z'
      lastUpdateTime: '2022-06-26T19:22:52Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2022-06-26T19:21:26Z'
      lastUpdateTime: '2022-06-26T19:22:52Z'
      message: >-
        ReplicaSet "argocd-ace-server-2-is-57796dd475" has successfully
        progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 10
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
