apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ace-demo-10
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: all-in-one-server
        tbn_cluster: all-in-one-server
        app: all-in-one-server
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/auto-poc/custom-ace-img:6.0
        imagePullPolicy: always
        name:ace-demo-10
        ports:
        - containerPort: 7800
          name: http
          protocol: TCP
