apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ace-demo-10
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: ce-demo-10
        tbn_cluster: ce-demo-10
        app: ce-demo-10
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/auto-poc/custom-ace-img:6.0
        imagePullPolicy: always
        name: ace-demo-10
        ports:
        - containerPort: 7800
          name: http
          protocol: TCP
