apiVersion: apps/v1
kind: Deployment
metadata:
  name: ace-server-argocd-10
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ace-server-argocd-10
  template:
    metadata:
      labels:
        app: ace-server-argocd-10
    spec:
      containers:
      - name: ace-server-argocd
        image: image-registry.openshift-image-registry.svc:5000/auto-poc/custom-ace-img:6.0
        ports:
        - containerPort: 8080
        env:
        - name: LICENSE_LICENSE
          value: L-KSBM-C87FU2
        - name: LICENSE_USE
          value: CloudPakForIntegrationNonProduction
        - name: OPERAND_VERSION
          value: 12.0.2.0-r2
        - name: LICENSE
          value: accept
