apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  pod:
    containers:
      runtime:
        image: image-registry.openshift-image-registry.svc:5000/auto-poc/custom-ace-img:5.0
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 300m
            memory: 350Mi
          requests:
            cpu: 300m
            memory: 300Mi
