apiVersion: apps/v1
kind: Deployment
metadata:
  name: ace-server-deplyment
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ace-server-deplyment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ace-server-deplyment
    spec:
      containers:
      - env:
	- name: LICENSE_LICENSE
	  value: L-KSBM-C87FU2
	- name: LICENSE_USE
	  value: CloudPakForIntegrationNonProduction
	- name: OPERAND_VERSION
	  value: 12.0.2.0-r2
        image: image-registry.openshift-image-registry.svc:5000/auto-poc/custom-ace-img:6.0
        imagePullPolicy: Always
        name: ace-server-deplyment
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: certs
        secret:
          defaultMode: 420
          secretName: ibm-jks
