apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: argocd-ace-server
  namespace: cp4i
spec:
  enableMetrics: true
  license:
    accept: true
    license: L-KSBM-C87FU2
    use: CloudPakForIntegrationNonProduction
  pod:
    containers:
      runtime:
        image: image-registry.openshift-image-registry.svc:5000/cp4i/custom-ace-img:5.0
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 300m
            memory: 350Mi
          requests:
            cpu: 300m
            memory: 300Mi
  adminServerSecure: false
  router:
    timeout: 120s
  designerFlowsOperationMode: disabled
  createDashboardUsers: true
  service:
    endpointType: http
  replicas: 1
  version: 12.0.2.0-r2