apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: auto-poc
resources:
- ace-server-dep.yaml
images:
- name: image-registry.openshift-image-registry.svc:5000/auto-poc/custom-ace-img
  newTag: "8"
